//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AnvilExtTest.rc
//
#define IDR_MAINFRAME                   1000
#define IDE_STOCK                       1000
#define IDS_BID_1                       1001
#define IDD_MARKETMAKER                 1001
#define IDS_BID_2                       1002
#define IDD_LOAD                        1002
#define IDS_BID_3                       1003
#define IDD_SENDORDER                   1003
#define IDS_BID_4                       1004
#define IDD_CANCELORDER                 1004
#define IDS_BID_5                       1005
#define IDD_INDEX                       1005
#define IDS_BID_6                       1006
#define IDD_SENDSTOPORDER               1006
#define IDS_ASK_1                       1007
#define IDD_POS_ORDERS_EXECS            1007
#define IDS_ASK_2                       1008
#define IDD_SINGLE_BOOK                 1008
#define IDS_ASK_3                       1009
#define IDD_MULTI_BOOK                  1009
#define IDS_ASK_4                       1010
#define IDS_ASK_5                       1011
#define IDS_ASK_6                       1012
#define IDS_LAST_NAME                   1013
#define IDS_LAST_VALUE                  1014
#define IDS_SIZE_NAME                   1015
#define IDS_SIZE_VALUE                  1016
#define IDS_NET_NAME                    1017
#define IDS_NET_VALUE                   1018
#define IDS_TIME_NAME                   1019
#define IDS_TIME_VALUE                  1020
#define IDS_VOLUME_NAME                 1021
#define IDS_VOLUME_VALUE                1022
#define IDS_BXA_NAME                    1023
#define IDS_BXA_VALUE                   1024
#define IDS_HI_NAME                     1025
#define IDS_HI_VALUE                    1026
#define IDS_LO_NAME                     1027
#define IDS_LO_VALUE                    1028
#define IDS_OPEN_NAME                   1029
#define IDS_OPEN_VALUE                  1030
#define IDS_MARKETOPEN_NAME             1030
#define IDS_CLOSE_NAME                  1031
#define IDS_CLOSE_VALUE                 1032
#define IDS_TICK_NAME                   1032
#define IDS_PRINT_1                     1033
#define IDS_PRINT_2                     1036
#define IDS_PRINT_3                     1037
#define IDS_PRINT_4                     1038
#define IDS_PRINT_5                     1039
#define IDS_PRINT_6                     1040
#define IDS_PRINTS_NAME                 1041
#define IDS_BIDTICK_NAME                1042
#define IDS_BIDTICK_VALUE               1043
#define IDE_PRICE_FROM_DOLLARS          1044
#define IDSP_PRICE_FROM_DOLLARS         1045
#define IDE_PRICE_FROM_CENTS            1046
#define IDSP_PRICE_FROM_CENTS           1047
#define IDS_PRICE_FROM_DOLLAR           1048
#define IDS_PRICE_FROM_CENT             1049
#define IDE_PRICE_TO_DOLLARS            1050
#define IDSP_PRICE_TO_DOLLARS           1051
#define IDE_PRICE_TO_CENTS              1052
#define IDSP_PRICE_TO_CENTS             1053
#define IDS_PRICE_TO_DOLLAR             1054
#define IDS_PRICE_TO_CENT               1055
#define IDG_PRICE                       1056
#define IDS_PRICE_FROM                  1057
#define IDS_PRICE_TO                    1058
#define IDS_MARKET_LOADED_NAME          1059
#define IDS_MARKET_LOADED               1060
#define IDL_STOCKS                      1061
#define IDS_STOCKS_LOADED_NAME          1062
#define IDE_SENDORDER_SYMBOL            1062
#define IDS_STOCKS_LOADED               1063
#define IDS_SENDORDER_SYMBOL            1063
#define IDE_SENDORDER_DESTINATION       1064
#define IDS_STOCKS_SUBSCRIBED_NAME      1064
#define IDS_SENDORDER_DESTINATION       1065
#define IDS_STOCKS_SUBSCRIBED           1065
#define IDE_SENDORDER_PRICE_DOLLARS     1066
#define IDS_SENDORDER_PRICE             1067
#define IDS_SENDORDER_PRICE_DOLLAR      1068
#define IDE_SENDORDER_PRICE_CENTS       1069
#define IDS_SENDORDER_PRICE_CENT        1070
#define IDE_SENDORDER_PRICE_TENTHS      1071
#define IDS_SENDORDER_PRICE_TENTH       1072
#define IDE_SENDORDER_SIZE              1073
#define IDS_SENDORDER_SIZE              1074
#define IDC_SENDORDER_TIF               1075
#define IDE_SENDORDER_TIF_MINUTES       1076
#define IDS_SENDORDER_TIF_MINUTES       1077
#define IDS_SENDORDER_TIF               1078
#define IDB_SENDORDER_HIDDEN            1079
#define IDE_SENDORDER_VISIBLESIZE       1080
#define IDS_SENDORDER_VISIBLESIZE       1081
#define IDB_SENDORDER_BUY               1082
#define IDB_SENDORDER_SELL              1083
#define IDB_CANCELORDER_SINGLE          1083
#define IDB_CANCELORDER_MULTIPLE        1084
#define IDE_SENDORDER_STOPPRICE_DOLLARS 1084
#define IDB_SENDORDER_LISTED_NYSE       1084
#define IDE_CANCELORDER_ID              1085
#define IDS_SENDORDER_STOPPRICE         1085
#define IDB_SENDORDER_LISTED_NYSE_NX    1085
#define IDS_CANCELORDER_ID              1086
#define IDS_SENDORDER_STOPPRICE_DOLLAR  1086
#define IDB_SENDORDER_LISTED_AMEX       1086
#define IDB_CANCELORDER_SINGLE_STOCK    1087
#define IDE_SENDORDER_STOPPRICE_CENTS   1087
#define IDB_SENDORDER_LISTED_DEFAULT    1087
#define IDB_CANCELORDER_ALL_STOCKS      1088
#define IDS_SENDORDER_STOPPRICE_CENT    1088
#define IDE_CANCELORDER_STOCKSYMBOL     1089
#define IDE_SENDORDER_STOPPRICE_TENTHS  1089
#define IDS_CANCELORDER_STOCKSYMBOL     1090
#define IDS_SENDORDER_STOPPRICE_TENTH   1090
#define IDB_CANCELORDER_BUY             1091
#define IDB_SENDSTOPORDER_PRICE         1091
#define IDB_CANCELORDER_SELL            1092
#define IDS_INDEX_SYMBOL_NAME           1092
#define IDB_SENDSTOPORDER_SAMESIDEQUOTE 1092
#define IDB_CANCELORDER_DAY             1093
#define IDE_INDEX_SYMBOL                1093
#define IDB_SENDSTOPORDER_OPPOSITESIDEQUOTE 1093
#define IDB_CANCELORDER_NONDAY          1094
#define IDS_VALUE_NAME                  1094
#define IDB_SENDSTOPORDER_PQD_ISLD      1094
#define IDB_CANCELORDER_SINGLE_DESTINATION 1095
#define IDS_VALUE                       1095
#define IDB_SENDSTOPORDER_PQD_SIZE      1095
#define IDB_CANCELORDER_ALL_DESTINATIONS 1096
#define IDS_NETCHANGE_NAME              1096
#define IDE_CANCELORDER_MMID            1097
#define IDS_NETCHANGE                   1097
#define IDS_CANCELORDER_MMID            1098
#define IDS_HIGH_NAME                   1098
#define IDS_HIGH                        1099
#define IDB_CANCELORDER_INCLUDE_SMART   1099
#define IDS_LOW_NAME                    1100
#define IDS_LOW                         1101
#define IDS_INDEX_SYMBOL                1102
#define IDS_CLOSE                       1103
#define IDB_DYNAMIC_UPDATE              1104
#define IDG_TRIGGER                     1105
#define IDG_SIDE                        1106
#define IDL_POSITIONS                   1106
#define IDS_OPEN                        1107
#define IDG_POST_QUOTE_DESTINATION      1107
#define IDL_ORDERS                      1107
#define IDS_MARKETOPEN                  1108
#define IDL_EXECUTIONS                  1108
#define IDS_TICK                        1109
#define IDS_POSITIONS_NAME              1109
#define IDS_ORDERS_NAME                 1110
#define IDS_EXECUTIONS_NAME             1111
#define IDS_POSITION_SYMBOL             1112
#define IDS_POSITION_OPEN_PNL           1113
#define IDS_POSITION_SIZE               1114
#define IDS_ORDER_SYMBOL                1115
#define IDS_EXECUTION_SYMBOL            1116
#define IDS_ORDER_ID                    1117
#define IDS_ORDER_SIZE                  1118
#define IDS_EXECUTION_ORDER_SIZE        1119
#define IDS_EXECUTION_ORDER_PRICE       1119
#define IDS_EXECUTION_SIZE              1120
#define IDS_POSITION_CLOSED_PNL         1121
#define IDS_POSITION_PENDING_BUY_ORDER_COUNT 1122
#define IDS_POSITION_PENDING_SELL_ORDER_COUNT 1123
#define IDG_LISTED                      1123
#define IDS_ORDER_EXEC_SIZE             1124
#define IDB_SINGLEBOOK_ISLD             1124
#define IDS_ORDER_PRICE                 1125
#define IDB_SINGLEBOOK_BATS             1125
#define IDS_ORDER_EXEC_PRICE            1126
#define IDB_SINGLEBOOK_ARCA             1126
#define IDS_ORDER_DESTINATION           1127
#define IDB_SINGLEBOOK_NYSE             1127
#define IDS_ORDER_TIF                   1128
#define IDB_SINGLEBOOK_DYNAMIC          1128
#define IDS_ORDER_TIME                  1129
#define IDB_SINGLEBOOK_AGGREGATED       1129
#define IDS_EXECUTION_TIME              1130
#define IDB_SINGLEBOOK_EXPANDED         1130
#define IDS_EXEC_ORDER_ID               1131
#define IDG_SINGLEBOOK_ID               1131
#define IDS_EXECUTION_PRICE             1132
#define IDG_SINGLEBOOK_DETAIL           1132
#define IDS_ORDER_SIDE                  1133
#define IDS_STOCK                       1133
#define IDB_MULTIBOOK_ISLD              1134
#define IDB_MULTIBOOK_BATS              1135
#define IDB_ECN_PRINTS                  1135
#define IDB_MULTIBOOK_ARCA              1136
#define IDB_MM_PRINTS                   1136
#define IDB_MULTIBOOK_NYSE              1137
#define IDS_ORDER_STATUS                1138
#define IDB_STOPLOSS_ONLY               1139
#define IDM_ACCOUNT                     32771
#define IDM_POSITIONS                   32772
#define IDM_ORDERS                      32773
#define IDM_QUOTES                      32774
#define IDM_BOOKQUOTES                  32775
#define IDM_AGRBOOKQUOTES               32776
#define IDM_LEVEL1                      32777
#define IDM_SUBSCRIPTION                32778
#define IDM_LOADSTOCKS                  32779
#define IDM_SENDORDER                   32780
#define IDM_CANCELORDER                 32781
#define IDM_INDEX                       32782
#define IDM_SENDSTOPORDER               32783
#define IDM_POS_ORDERS_EXECS            32784
#define IDM_SINGLEBOOK                  32785
#define IDM_MULTIBOOK                   32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1010
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1140
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
