//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearchLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResearchLib {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResearchLib() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResearchLib.Properties.ResearchLib", typeof(ResearchLib).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAAB
        ///AABC
        ///AACB
        ///AACE
        ///AAII
        ///AALA
        ///AAME
        ///AANB
        ///AAON
        ///AAON
        ///AAPL
        ///AATK
        ///AAUK
        ///ABAX
        ///ABBK
        ///ABCB
        ///ABCO
        ///ABCW
        ///ABER
        ///ABFI
        ///ABFS
        ///ABGX
        ///ABIX
        ///ABIZ
        ///ABLE
        ///ABMC
        ///ABMD
        ///ABRI
        ///ABTL
        ///ABWG
        ///ACAI
        ///ACAM
        ///ACAP
        ///ACAS
        ///ACAT
        ///ACBA
        ///ACCL
        ///ACDO
        ///ACEC
        ///COMM
        ///ACET
        ///ACGL
        ///ACHI
        ///ACLA
        ///ACLO
        ///ACLS
        ///ACME
        ///ACME
        ///ACMR
        ///ACPW
        ///ACRI
        ///ACRN
        ///ACRT
        ///ACRU
        ///ACTI
        ///ACTL
        ///ACTM
        ///ACTN
        ///ACTP
        ///ACTR
        ///ACTT
        ///ACTU
        ///ACXM
        ///ADAM
        ///ADAT
        ///ADBE
        ///ADBI
        ///ADBL
        ///ADCT
        ///ADEX
        ///ADGO
        ///ADIC
        ///ADLI
        ///ADLR
        ///ADLT
        ///ADPI
        ///ADPT
        ///ADRX
        ///ADSC
        ///ADSK
        ///ADST
        ///ADSX
        ///ADTK
        ///ADTN
        ///ADVP
        ///ADVS
        ///ADYN
        ///AEGN
        ///AEHR
        ///AEIS
        ///AELA
        ///AEOS
        ///AEPI
        ///AERS
        ///AESP
        ///AETC
        ///AETH
        ///AFAM
        ///AFBC
        ///AFCE
        ///AFCI
        ///AFCO
        ///AF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nasdaq {
            get {
                return ResourceManager.GetString("nasdaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACN
        ///ACE
        ///ACE
        ///ACG
        ///ACM
        ///ADX
        ///ASF
        ///RKY
        ///AMD
        ///ATE
        ///AEG
        ///AET
        ///AMG
        ///ASV
        ///AEM
        ///AGU
        ///APD
        ///ARG
        ///ANS
        ///AOS
        ///RNT
        ///ANF
        ///ABM
        ///ABM
        ///AKR
        ///AKS
        ///APS
        ///AIN
        ///ACV
        ///ARE
        ///AYE
        ///ALN
        ///ALE
        ///ADS
        ///AIQ
        ///ATK
        ///AIB
        ///AFC
        ///ALS
        ///AMB
        ///AMB
        ///AIZ
        ///DOX
        ///AEE
        ///AWA
        ///AEP
        ///AFG
        ///MRF
        ///PLB
        ///AMZ
        ///ARL
        ///ASI
        ///AWR
        ///AWK
        ///APU
        ///AHM
        ///AME
        ///AMR
        ///AMR
        ///ASO
        ///ADI
        ///AXE
        ///ANN
        ///AOL
        ///AOL
        ///APA
        ///AOT
        ///ABI
        ///AHG
        ///ATR
        ///ARB
        ///ACI
        ///ASN
        ///AGY
        ///ACK
        ///AJG
        ///ASA
        ///ASA
        ///ASH
        ///GRR
        ///AZN
        ///PLC
        ///AWE
        ///FDY
        ///ATO
        ///AOR
        ///ALV
        ///AVB
        ///AVE
        ///AVL
        ///AVT
        ///AVX
        ///AVX
        ///AZR
        ///AIF
        ///ATU
        ///ADO
        ///PVD
        ///MKT
        ///ASX
        ///AES
        ///AES
        ///ACS
        ///AFL
        ///ATG
        ///AGL
        ///ADC
        ///AHO
        ///ABF
        ///FLY
        ///AGE
        ///AIR
        ///AAR
        ///ABT
        ///ABY
        ///ABN
        ///ABN
        ///AAI
        ///ALG
        ///ALK
        ///ALB
        ///ABS
        ///ALA
        ///ALX
        ///ATI
        ///AGN
        ///AGI
        ///LNT
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nyse {
            get {
                return ResourceManager.GetString("nyse", resourceCulture);
            }
        }
    }
}
