//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTradeLink.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestTradeLink.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Symbol=WAG
        ///; Date=09/26/07-09/26/07
        ///Q,070926,041502,43.81,51.2,1,1,PSE ,PSE 
        ///Q,070926,041502,43.81,47.05,1,1,PSE ,PSE 
        ///Q,070926,065043,46.89,47.05,1,1,PSE ,PSE 
        ///Q,070926,065445,43.81,46.89,1,14,PSE ,PSE 
        ///T,070926,065446,46.89,100,PSE 
        ///Q,070926,065606,43.81,47.05,1,1,PSE ,PSE 
        ///Q,070926,070027,43.81,46.89,1,3,PSE ,NMS 
        ///Q,070926,070047,43.81,46.6,1,5,PSE ,NMS 
        ///Q,070926,070203,46,46.6,1,5,PSE ,NMS 
        ///Q,070926,073528,46.35,46.6,1,5,PSE ,NMS 
        ///Q,070926,073602,46.35,46.88,1,1,PSE ,PSE 
        ///Q,070926,073602, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestWAG {
            get {
                return ResourceManager.GetString("TestWAG", resourceCulture);
            }
        }
    }
}
