//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQFeedBroker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IQFeedBroker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	NMS	Nasdaq National Market
        ///2	SMCAP	Small Capital Market
        ///3	OTC	Nasdaq other OTC
        ///4	OTCBB	Nasdaq OTC Bulletin Board
        ///5	NASDAQ	Nasdaq
        ///6	NYSE_AMEX	NYSE American Exchange
        ///7	NYSE	New York Stock Exchange
        ///8	CHX	Chicago Stock Exchange
        ///9	PHLX	Philadelphia Stock Exchange
        ///10	NSX	National Stock Exchange
        ///11	ARCA	NYSE Archipelago
        ///12	BX	Boston Stock Exchange
        ///13	CBOE	Chicago Board Options Exchange
        ///14	OPRA	OPRA System
        ///15	NASD_ADF	Nasdaq Alternate Display facility
        ///16	ISE	International Stock Exchange
        ///17	BOX	Bos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string marketcenters {
            get {
                return ResourceManager.GetString("marketcenters", resourceCulture);
            }
        }
    }
}
