//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeLink.Research.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradeLink.Research.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAAB
        ///AABC
        ///AACB
        ///AACE
        ///AAII
        ///AALA
        ///AAME
        ///AANB
        ///AAON
        ///AAON
        ///AAPL
        ///AATK
        ///AAUK
        ///ABAX
        ///ABBK
        ///ABCB
        ///ABCO
        ///ABCW
        ///ABER
        ///ABFI
        ///ABFS
        ///ABGX
        ///ABIX
        ///ABIZ
        ///ABLE
        ///ABMC
        ///ABMD
        ///ABRI
        ///ABTL
        ///ABWG
        ///ACAI
        ///ACAM
        ///ACAP
        ///ACAS
        ///ACAT
        ///ACBA
        ///ACCL
        ///ACDO
        ///ACEC
        ///COMM
        ///ACET
        ///ACGL
        ///ACHI
        ///ACLA
        ///ACLO
        ///ACLS
        ///ACME
        ///ACME
        ///ACMR
        ///ACPW
        ///ACRI
        ///ACRN
        ///ACRT
        ///ACRU
        ///ACTI
        ///ACTL
        ///ACTM
        ///ACTN
        ///ACTP
        ///ACTR
        ///ACTT
        ///ACTU
        ///ACXM
        ///ADAM
        ///ADAT
        ///ADBE
        ///ADBI
        ///ADBL
        ///ADCT
        ///ADEX
        ///ADGO
        ///ADIC
        ///ADLI
        ///ADLR
        ///ADLT
        ///ADPI
        ///ADPT
        ///ADRX
        ///ADSC
        ///ADSK
        ///ADST
        ///ADSX
        ///ADTK
        ///ADTN
        ///ADVP
        ///AD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nasdaq {
            get {
                return ResourceManager.GetString("nasdaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A|00846U101|Agilent Technologies, Inc. Common Stock|ELECTRONICS-SEMICONDUCTORS AND OTHER COMPONENTS|114A|
        ///AA|013817101|Alcoa Inc. Common Stock|MINING,REFINING,FABRICATING-ALUMINUM|130A|
        ///AAI|00949P108|AirTran Holdings, Inc. Common Stock|AIR-PASSENGER AIRLINES|202A|
        ///AAP|00751Y106|Advance Auto Parts, Inc. Common Stock|RETAIL TRADE-OTHER RETAIL OPERATIONS|146G|
        ///AAR|001765866|AMR Corporation 7.875% Public Income NotES(PINES) due July 13, 2039|AIR-PASSENGER AIRLINES|202A|
        ///AAV|00762L101|Advantage Energy Incom [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nyse {
            get {
                return ResourceManager.GetString("nyse", resourceCulture);
            }
        }
    }
}
